# Generated by Django 4.1.6 on 2023-03-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_created_at_room_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='AABCDE', max_length=8, unique=True),
        ),
    ]
