# Generated by Django 4.1.7 on 2023-07-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_room_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="currentSong",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
